version: "3.8"
services:
  postgres-db:
    image: postgres:15.3-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres-db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_MODE: "False"  # Configuração para desativar o modo de servidor
      PGADMIN_DEFAULT_SERVER: "postgres-db"  # Nome do serviço do PostgreSQL no Docker Compose
      PGADMIN_DEFAULT_DATABASE: "devwebapi-db"
      PGADMIN_DEFAULT_USERNAME: "postgres"
    ports:
      - 8089:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

#networks:
#  default:
#    name: local-network
#    external: true